site_name: Grains of Insight
site_url: https://andreavitaletti.github.io/Grains-of-Insight

# repo_url: https://github.com/andreavitaletti/IoT_short_course

theme:
  name: 'material'
  # logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    primary: lime

markdown_extensions:
  - pymdownx.critic
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  # - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - gh-admonitions

nav:
    - Home: index.md

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/TZhMmbgq
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/andrea-vitaletti-3651442/

copyright: Created by Andrea Vitaletti.<br/><img alt="" style="border-width:0" src="https://andreavitaletti.github.io/IoT_short_course/assets/images/mail.png" /></br><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>
